[package]
name = "e02-crowdfunding-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.e02-crowdfunding]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.35.0"
