[package]
name = "mycrowdfunding-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.mycrowdfunding]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.35.0"
